# Basic Information 
title: Junteng Liu
position: Ph.D. Candidate
affiliation: Hong Kong University of Science and Technology
email: jliugi@connect.ust.hk
github_username: Vicent0205
twitter_username: junteng88716710
google_scholar: https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate
description: "First-year PhD candidate at HKUST NLP Group. Research focuses on natural language processing and machine learning."

# Site Settings
locale: "en-US"
title_separator: "-"
url: "https://jacken-hubman-du.github.io"
baseurl: "/LJT-Homepage"
repository: "jacken-hubman-du/LJT-Homepage"

# Site Author
author:
  name: "Junteng Liu"
  avatar: 
  bio: "First-year PhD candidate at HKUST NLP Group, advised by Professor Junxian He. Research focuses on natural language processing and machine learning."
  location: 
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jliugi@connect.ust.hk"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vicent0205"
    - label: "X"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/junteng88716710"

# Operating System
# -------------
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processors
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Permalinks
permalink: /:categories/:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: /page:num/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comment: true

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path

# Site Map
sitemap:
  enabled: true

# Analytics
analytics:
  provider: false

# Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jliugi@connect.ust.hk"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vicent0205"
    - label: "X"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/junteng88716710"
